### 
# @name Login
GET  {{hostname}}/Api/User/Login/admin/123456 
Content-Type: application/json

###
Get {{hostname}}/Api/User/FindAllUsers
Content-Type: application/json
Authorization: Bearer {{Login.response.body.$.data.token}}